### ISSUE TITLE
No license file

### ISSUE THREAD

**Issue by dcforeman** [LeeBamberTGC/FPS-Creator-Classic#149]
Hi,

There's no obvious license file, I know it's open source but which license has the code been released under?

Thanks!

**Comment by LeeBamberTGC** [comment]
Added missing EXE and DLL files

**Comment by quantum-entangler** [comment]
Indeed I can't find any open source licensing terms at the [home page](https://www.thegamecreators.com/product/fps-creator-classic-open-source) either. For the time being its likely safe to assume that some sort of EULA applies, in which case calling this Open Source does seem very misleading.

I can however certainly understand that it can be difficult to choose which [license](https://opensource.org/licenses/category) might work the best for the copyright owners. I do hope that will be solved in time. In the meanwhile however it probably wouldn't hurt to re-open this issue and perhaps inquire with your own user community about what they would like to see in terms of the licensing while you research your licensing options.

Cheers.
