### ISSUE TITLE
Issues with compile instructions

### ISSUE THREAD

**Issue by dcforeman** [LeeBamberTGC/FPS-Creator-Classic#150]
Cloned the repo, instructions stated 

1. Launch DBP using this path: 'Dark Basic Pro Shared\Dark Basic Pro\Launch.exe'

There is no Launch.exe file, there is only a Launch,cfg

I went into the editor folder, there is no EXE for the IDE, massive amounts of missing files.
Went into compiler folder, there is no DBPCompiler.exe

**Comment by LeeBamberTGC** [comment]
Added missing EXE and DLL files

**Comment by dcforeman** [comment]
Has a license file been added?
